No need to background the job...

diff --git a/youtube-mp3 b/youtube-mp3
--- a/youtube-mp3
+++ b/youtube-mp3
@@ -18,30 +18,28 @@
 
 cd "$HOME/tmp" || exit 1
 
-export d=${1:-$(zenity --entry --width=1000)} || exit 1
+d=${1:-$(zenity --entry --width=1000)} || exit 1
 
 [ -z "$d" ] && exit 1
-(
-	title=$(youtube-dl --verbose --get-title "$d")
-	if [ $? -ne 0 ]; then
-		# In case you get this ERROR message, just start it on the command
-		# line and look at the outputs to try to understand and maybe fix
-		# the problem by yourself
 
-		notify-send -u critical -a youtube-mp3 "ERROR !" "Cannot download '$d'"
-		exit 1
-	fi
+title=$(youtube-dl --verbose --get-title "$d")
+if [ $? -ne 0 ]; then
+	# In case you get this ERROR message, just start it on the command
+	# line and look at the outputs to try to understand and maybe fix
+	# the problem by yourself
 
-	notify-send -u low -a youtube-mp3 "Processing ..." "$title"
+	notify-send -u critical -a youtube-mp3 "ERROR !" "Cannot download '$d'"
+	exit 1
+fi
 
-	mp3=$(\
-	 youtube-dl --extract-audio --audio-format=mp3 --audio-quality=192K "$d" \
-	 | tee /dev/stderr \
-	 | sed -ne '/.* Destination:/ s/.* Destination: \(.*\.mp3\).*/\1/ p'\
-	)
+notify-send -u low -a youtube-mp3 "Processing ..." "$title"
 
-	if [ $? -eq 0 ]; then
-		notify-send -u low      -a youtube-mp3 -t 30000 "Done" "$mp3"
-	else	notify-send -u critical -a youtube-mp3 -t 30000 "Failed !" "$mp3"; fi
-) &
-tty -s && wait
+mp3=$(\
+ youtube-dl --extract-audio --audio-format=mp3 --audio-quality=192K "$d" \
+ | tee /dev/stderr \
+ | sed -ne '/.* Destination:/ s/.* Destination: \(.*\.mp3\).*/\1/ p'\
+)
+
+if [ $? -eq 0 ]; then
+	notify-send -u low      -a youtube-mp3 -t 30000 "Done" "$mp3"
+else	notify-send -u critical -a youtube-mp3 -t 30000 "Failed !" "$mp3"; fi
